dashboard/urls.py
from django.urls import path
from dashboard import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from dashboard.views import export_data, import_data
from django.views.static import serve 



urlpatterns = [
    
    path('index/',views.index, name='index'),
    path('add_record/', views.add_record, name='add_record'),
    path('performance/', views.performance, name='performance'),
    path('show_record/', views.show_record, name='show_record'),
    path('edit_policy/<int:id>', views.edit_policy,name='edit_policy'),
    path('view_policy/<int:id>', views.view_policy,name='view_policy'),
    path('update_policy/<int:id>', views.update_policy,name='update_policy'),
    #path("delete_policy",views.delete_policy, name="delete_policy"),
    path('delete_policy/<int:id>', views.delete_policy,name='delete_policy'),      
    path('search_record/', views.SearchResultsView.as_view(),name='search_record'),
    path('search-file/', views.SearchView.as_view(),name='search-file'),
    path('sort_record/', views.sort_record, name='sort_record'),
    #path('csv/',views.getfile),
    #path('excel_import/',views.excel_import, name="excel_import"), 
    path('export/', export_data, name="export_data"),
    path('import/', import_data, name="import_data"),
    path('my-drive/', views.my_drive, name='my-drive'),
    path('add-policy/', views.add_policy, name='add-policy'),
    path('delete_drive/<int:id>', views.delete_drive,name='delete_drive'), 
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
   

    
]

pms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	
    path('admin/', admin.site.urls),
	path('',include('home.urls')),
	path('',include('dashboard.urls')),
	path('account/',include('account.urls')),	

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from time import sleep
import datetime
from datetime import datetime


STATUS=((0,'Deactive'),(1,'Active'))
# POLICY_TYPES=(
# (0,"jan_dhan_yojna"),
# (1,"jivan_bima"),
# (2,"jivan_laabh"),

#     )

PAY_FOR=(
("quarterly","Quarterly"),
("six_month","Six Month"),
("yearly","Yearly"),

)


class PolicyType(models.Model):
    policy_type = models.CharField(max_length=50)
    added_on =models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.policy_type


class Lic(models.Model):    
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email= models.EmailField(max_length=50)
    dob=models.CharField(max_length=50)
    contact=models.CharField(max_length=50)
    address_line_one=models.CharField(max_length=100)
    address_line_two=models.CharField(max_length=100)
    lendmark=models.CharField(max_length=100,default=None)
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    policy_type=models.ForeignKey('PolicyType',on_delete=models.CASCADE,related_name='PolicyType')
    policy_number=models.CharField(unique=True,null=False,max_length=10)
    premium=models.IntegerField()
    sum_assured=models.IntegerField()
    year_of_policy=models.IntegerField()
    pay_for=models.CharField(choices=PAY_FOR,null=False,max_length=50)
    beneficiary_name=models.CharField(max_length=50)
    created_on=models.CharField(max_length=50)
    renew_date=models.CharField(max_length=20)
    status=models.IntegerField(choices=STATUS,default=1)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
    	return self.first_name

    

       
class Drive(models.Model):
    file_name = models.CharField(max_length=20)
    file = models.FileField()
    added_on =models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    


    def __str__(self):
        return self.file_name
   

   
       

dashboard/forms.py
from django import forms  
from.models import *
from django.contrib.auth.models import User  
#from Admin.models import Designations,Salary


class ContactForm(forms.Form):		
	name=forms.CharField(required=True)
	email=forms.CharField(required=True)
	phone_number=forms.CharField(required=True)
	message=forms.CharField()



class File_Upload(forms.ModelForm):  
    class Meta:  
        model = Drive  
        fields = ['file_name','file']  	

dashboard/views.py
from django.shortcuts import render, redirect  
from django.http import HttpResponse,HttpResponseRedirect  
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, BadHeaderError
from pms import settings  
from django.utils.decorators import method_decorator
import csv
from django.core.paginator import Paginator
from .models import Lic,PolicyType
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from django import template
from django.contrib.auth.models import User
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from dashboard.models import Lic,Drive
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.contrib import messages
from datetime import datetime, timedelta
from django.conf import settings
from account.models import register_table
from pms.settings import MAIL
from django.utils import timezone
from reportlab.pdfgen import canvas  
from django.http import HttpResponse  
from django.http import FileResponse
#from pms.settings import register_pms
import xlwt 
from dashboard.functions import handle_uploaded_file  
from .resources import LicResource
from tablib import Dataset
from .forms import File_Upload 


@login_required
def index(request):
    user = User.objects.get(username = request.user)
    lics = Lic.objects.filter(user__pk=user.id)
    userMail=request.user.get_username()
    duesInTwoDays= Lic.objects.filter(user__pk=user.id,renew_date__range=[datetime.now().date(),datetime.now().date()+timedelta(days=2)],status=1).order_by('renew_date')
    duesInWeek= Lic.objects.filter(user__pk=user.id,renew_date__range=[datetime.now().date(),datetime.now().date()+timedelta(days=7)],status=1).order_by('renew_date')
    
    reminder7day= Lic.objects.filter(user__pk=user.id,renew_date=datetime.now().date()+timedelta(days=7),status=1)     
    for i in reminder7day:
            print(i.email)
            MAIL(i.email)

    reminder2day= Lic.objects.filter(user__pk=user.id,renew_date=datetime.now().date()+timedelta(days=2),status=1)     
    for i in reminder2day:
            print(i.email)
            MAIL(i.email)
    
    
    return render(request,'dashboard/index.html',{
        'towDaysDues':duesInTwoDays,
        'weekDues':duesInWeek
        })



@login_required
def performance(request):
    return render(request,"dashboard/performance.html")




@login_required
def add_record(request):
    if request.method == "POST":
        user = User.objects.get(username = request.user)
        first_name  = request.POST.get('first_name') 
        last_name  = request.POST.get('last_name')
        email = request.POST.get('email')
        dob = request.POST.get('dob')
        contact =request.POST.get('contact')
        address_line_one = request.POST.get('address_line_one')
        address_line_two = request.POST.get('address_line_two')
        lendmark= request.POST.get('lendmark')
        city= request.POST.get('city')
        state= request.POST.get('state')
        policy_number=request.POST.get('policy_number')
        premium= request.POST.get('premium')
        sum_assured= request.POST.get('sum_assured')
        year_of_policy = request.POST.get('year_of_policy')
        pay_for = request.POST.get('pay_for')
        beneficiary_name =request.POST.get('beneficiary_name')
        created_on =request.POST.get('created_on')
        renew_date=request.POST.get('renew_date')
        policy_type=PolicyType.objects.get(policy_type=request.POST.get('type'))
        #status=request.POST.get('status')
        obj=Lic(email=email,first_name=first_name,last_name=last_name,address_line_one=address_line_one,address_line_two=address_line_two,lendmark=lendmark,city=city,state=state,
        dob=dob,contact=contact,policy_number=policy_number,
        premium=premium,sum_assured=sum_assured,year_of_policy=year_of_policy,pay_for=pay_for,beneficiary_name=beneficiary_name,
        created_on=created_on,renew_date=renew_date,policy_type=policy_type,user = user)
        obj.save()
        #register_pms(email) 
        messages.success(request, ' Successfully Saved ')
        return redirect("/show_record")                 
    policy_type=PolicyType.objects.all()
    return render(request,'dashboard/add_record.html',{'context':policy_type}) 
            


    
    
@login_required
def show_record(request):
    user = User.objects.get(username = request.user)   
    lics = Lic.objects.filter(user__pk=user.id)
    paginator=Paginator(lics,6)
    page_number= request.GET.get('page')
    page_obj =paginator.get_page(page_number)
    return render(request,'dashboard/show_record.html',{'page_obj':page_obj})   


@login_required
def edit_policy(request, id):  
    lics = Lic.objects.get(id=id) 
    policy_type=PolicyType.objects.all()
    return render(request,'dashboard/edit_policy.html', {'lics':lics,'context':policy_type})      


@login_required
def view_policy(request, id):  
    lics = Lic.objects.get(id=id) 
    return render(request,'dashboard/view_policy.html', {'lics':lics})      


@login_required
def add_policy(request):
    if request.method == "POST":
        user = User.objects.get(username = request.user)
        policy_type  = request.POST.get('policy_type')
        obj=PolicyType(policy_type=policy_type,user=user)
        obj.save()
        messages.success(request, ' Successfully Saved ')
        return redirect("/add-policy")

    return render(request,"dashboard/add_policy.html")



@login_required
def update_policy(request, id):  
    lics = Lic.objects.get(id=id)  
    if request.method == "POST":
        user = User.objects.get(username = request.user)
        lics.first_name  = request.POST.get('first_name','') 
        lics.last_name  = request.POST.get('last_name','')
        lics.email = request.POST.get('email','')
        lics.dob = request.POST.get('dob','')
        lics.contact =request.POST.get('contact','')
        lics.address_line_one = request.POST.get('address_line_one','')
        lics.address_line_two = request.POST.get('address_line_two','')
        lics.city=request.POST.get('city','')
        lics.state=request.POST.get('state','')
        lics.policy_number=request.POST.get('policy_number','')
        lics.premium= request.POST.get('premium','')
        lics.pay_for = request.POST.get('pay_for','')
        lics.sum_assured= request.POST.get('sum_assured','')
        lics.year_of_policy = request.POST.get('year_of_policy','')
        lics.beneficiary_name =request.POST.get('beneficiary_name','')
        lics.renew_date=request.POST.get('renew_date','')
        # lics.policy_type=request.POST.get('type','')
        lics.policy_type=PolicyType.objects.get(policy_type=request.POST.get('type',''))
        lics.status=request.POST.get('status','')
        lics.save()
        messages.success(request, ' Successfully Updated ')
    return redirect('/show_record')

    

@login_required
def delete_policy(request, id):  
    lics = Lic.objects.get(id=id)  
    lics.delete() 
    messages.success(request, 'Successfully Deleted')
    return redirect('/show_record')     




class SearchResultsView(ListView):
    model = Lic
    template_name = 'dashboard/search_results.html'
    
    def get_queryset(self):
        query = self.request.GET.get('q') # new
        object_list = Lic.objects.filter(
            Q(first_name__icontains=query) | Q(policy_number__icontains=query)
        )
        return object_list



class SearchView(ListView):
    model = Drive
    template_name = 'dashboard/search_file.html'
    
    def get_queryset(self):
        query = self.request.GET.get('qr') # new
        objects_list = Drive.objects.filter(
            Q(file='query')
        )
        print(objects_list)
        return objects_list





def sort_record(request):
    user = User.objects.get(username = request.user)
    sorting = request.GET.get('sorting')
    lics = Lic.objects.filter(user__pk=user.id)
    active = Lic.objects.filter(user__pk=user.id,status=1).count()
    count = lics.count()
    # print(sorting)
    if sorting =='status':
        lics = Lic.objects.filter(user__pk=user.id,status=1).order_by('renew_date')
        return render(request,'dashboard/show_record.html',{
            'lics':lics,
             'count':count,
             'active':active

            })  
    else:
    
        lics = Lic.objects.filter(user__pk=user.id).order_by('-'+sorting)
        return render(request,'dashboard/show_record.html',{
            'lics':lics,
            'count':count,
             'active':active
            })  


def export_data(request):
    user = User.objects.get(username = request.user)
    if request.method == 'POST':
        file_format = request.POST['file-format']
        lic_resource = LicResource()
        queryset = Lic.objects.filter(user__pk=user.id)
        dataset = lic_resource.export(queryset)
        
        if file_format == 'CSV':
            response = HttpResponse(dataset.csv, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="PmsData_Backup.csv"'
            return response        
        
        elif file_format == 'JSON':
            response = HttpResponse(dataset.json, content_type='application/json')
            response['Content-Disposition'] = 'attachment; filename="PmsData_Backup.json"'
            return response

        elif file_format == 'XLS (Excel)':
            response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename="PmsData_Backup.xls"'

dashboard/templates/dashboard/add_policy.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div class="container-fluid mt--7">
  <div class="row">
    <div class="col">
      <div class="card shadow">
        <div class="card-header bg-transparent">
          <h3 class="mb-0">Add New Policy-Type</h3>
        </div>
        <div class="card-body">
         <div class="container">
          <form name="myformcont" class="my-2" action="{% url 'add-policy' %}" method="POST">
            {% csrf_token %}
            <!-- <h2 class="text-center">LIC Form</h2> -->
            <div class="row jumbotron">

          <div class="col-sm-12 form-group" style="margin-top: -20px;">
            <label for="name">New Policy-Type :</label>
            <input type="text" class="form-control" name="policy_type" id="name-f" placeholder="Enter policy_type" required>
          </div>          
 
      <div class="col-sm-12 form-group mb-0">
       <button class="btn btn-primary float-right">Submit</button>
     </div>
     
   </div>
 </form>
</div> 
</div>
</div>
</div>
</div>

{% include "dashboard/footer.html" %}

</div>


{% endblock content %}

dashboard/templates/dashboard/add_record.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div class="container-fluid mt--7">
  <div class="row">
    <div class="col">
      <div class="card shadow">
        <div class="card-header bg-transparent">
          <h3 class="mb-0">Add New-Policy</h3>
        </div>
        <div class="card-body">
         <div class="container">
          <form name="myformcont" class="my-2" action="{% url 'add_record' %}" method="POST">
            {% csrf_token %}
            <!-- <h2 class="text-center">LIC Form</h2> -->
            <div class="row jumbotron">

          <div class="col-sm-12 form-group" style="margin-top: -20px;">
            <label for="name">First Name :</label>
            <input type="text" class="form-control" name="first_name" id="name-f" placeholder="Enter your First Name." required>
          </div>
          <div class="col-sm-12 form-group" style="margin-top: -20px;">
            <label for="name">Last Name :</label>
            <input type="text" class="form-control" name="last_name" id="name-f" placeholder="Enter your Last Name." required>
          </div>
          
          <div class="col-sm-12 form-group">
            <label for="email">Email :</label>
            <input type="text" class="form-control" name="email" id="name-l" placeholder="Enter your Email" required>
          </div>
          <div class="col-sm-6 form-group">
            <label for="Date">Date of Birth :</label>
            <input type="Date" name="dob" class="form-control" id="Date" placeholder="enter your date of birth" required>
          </div>
          <div class="col-sm-6 form-group">
            <label for="e_group">Contact No.</label>
            <input type="text" class="form-control" name="contact" id="name-f" placeholder="Enter your contact number" required>
          </div>
          <div class="col-sm-12 form-group">
            <label for="cost_center">Address Line 1</label>
            <input type="text" class="form-control" name="address_line_one" id="cost_center" placeholder="Enter your address " required>
          </div>
          <div class="col-sm-12 form-group">
            <label for="cost_center">Address Line 2</label>
            <input type="text" class="form-control" name="address_line_two" id="cost_center" placeholder="Enter your address" required>
          </div>
          <div class="col-sm-6 form-group">
        <label for="bname">Lendmark</label>
        <input type="text" class="form-control" name="lendmark" id="name-l" placeholder="Enter  Lendmark" required>
      </div>
          <div class="col-sm-6 form-group">
        <label for="bname">City</label>
        <input type="text" class="form-control" name="city" id="name-l" placeholder="Enter City" required>
      </div>
      <div class="col-sm-6 form-group">
        <label for="bname">State</label>
        <input type="text" class="form-control" name="state" id="name-l" placeholder="Enter  State" required>
      </div>
          
      <div class="col-sm-6 form-group">
        <label for="bname">Policy Number</label>
        <input type="text" class="form-control" name="policy_number" id="name-l" placeholder="Enter  policy number" required>
      </div>
      <div class="col-sm-6 form-group">
        <label for="Dname">Premium</label>
        <input type="text" class="form-control" name="premium" id="name-l" placeholder="Enter premium" required>
      </div>

      <div class="col-sm-6 form-group">
        <label for="type_of_policy">Pay For</label>
        <select id="inputType"  name="pay_for" class="form-control browser-default custom-select" required/>
        <!-- <option disabled>type of policy</option> -->
        <option disabled="true" selected="selected">-----Select ----</option>
        <option value="quarterly">Quarterly</option>
        <option value="six_month">Six Month</option>
        <option value="yearly">Yearly</option>
      </select>
    </div>

      <div class="col-sm-6 form-group">
        <label for="Payslip">Sum Assured</label>
        <input type="text" class="form-control" name="sum_assured" id="address-1" placeholder="enter sum assured" required>
      </div>
      
      
      <div class="col-sm-6 form-group">
        <label for="cc description">Year of Policy</label>
        <input type="text" class="form-control" name="year_of_policy" id="description" placeholder="Enter year of policy" required>
      </div>
      <div class="col-sm-6 form-group">
        <label for="pan_no"> Beneficiary Name</label>
        <input type="text" class="form-control" name="beneficiary_name" id="pan-no" placeholder="Enter beneficiary name" required>
      </div>
      <div class="col-sm-6 form-group">
        <label for="created_on">Created On</label>
        <input type="Date" class="form-control" name="created_on" id="pan-no" placeholder="Enter created on" required>
      </div>
      <div class="col-sm-6 form-group">
        <label for="renew_date">Renew Date</label>
        <input type="date" name="renew_date" data-date-format="DD-MM-YYYY" class="form-control datetimepicker" id="Date" placeholder="Enter renew date" required>
      </div>
      <div class="col-sm-6 form-group">
        <label for="type_of_policy">Policy Type</label>
        <select id="inputType"  name="type" class="form-control browser-default custom-select" required/>
        <!-- <option disabled>type of policy</option> -->
        <option disabled="true" selected="selected">-----Select Policy----</option>{% for obj in context %}
        <option value="{{obj.policy_type}}">{{obj.policy_type}}</option>
        {% endfor %}
       
      
      </select>
    </div>

      <div class="col-sm-12">
        <input type="checkbox" class="form-check d-inline" id="chb" required><label for="chb" class="form-check-label">&nbsp;I accept all terms and conditions.
        </label>
      </div>

      <div class="col-sm-12 form-group mb-0">
       <button class="btn btn-primary float-right">Submit</button>
     </div>
     
   </div>
 </form>
</div> 
</div>
</div>
</div>
</div>

{% include "dashboard/footer.html" %}

</div>


{% endblock content %}

dashboard/templates/dashboard/demo.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>



<button class="open-button" onclick="openForm()">Open Form</button>

<div class="form-popup" id="myForm">
  <form action="/action_page.php" class="form-container">
    <h1>Login</h1>

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <button type="submit" class="btn">Login</button>
    <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
  </form>
</div>

<script>
function openForm() {
  document.getElementById("myForm").style.display = "block";
}

function closeForm() {
  document.getElementById("myForm").style.display = "none";
}
</script>

</body>
</html>

dashboard/templates/dashboard/excel.html
  <form method="post" enctype="multipart/form-data" action="{% url 'excel_import' %}">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

dashboard/templates/dashboard/export.html
<h3>Export Data</h3>
<p>exporting from database</p>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Please select format of file.</p>
    <select name="file-format" class="form-control my-3">
        <option selected>Choose format...</option>
        <option>CSV</option>
        <option>JSON</option>
        <option>XLS (Excel)</option>
      </select>
    <button class="btn btn-primary" type="submit">Export</button>
  </form>

dashboard/templates/dashboard/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a target="_blank" 
                 href="#" 
                 class="font-weight-bold ml-1">P-M-S Dashboard </a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="#" 
                 class="font-weight-bold ml-1" target="_blank"> &copy;-Copyright-2020 PMS. All Rights Reserved</a> 
                  <!-- <a target="_blank" href="https://appseed.us?ref=ct-demo">AppSeed</a>. -->
            </div>
          </div>
        </div>
      </footer>

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{% block content %}

<style type="text/css">
  .table .thead-light th {
    background-color: #f6f9fc;
    color: black;
}
</style>

<div class="container-fluid mt--7">
  <!-- Table -->
  <div class="row">
    <div class="col">
      <div class="card shadow">
        <div class="card-header border-0">
          <div class="row align-items-center">
            <div class="col-md-6">
              <marquee behavior="scroll" direction="up" scrollamount="2"><h3 style="color: red" class="mb-0">Expire in 2 Days</h3></marquee>
              <br>
              <div class="table-responsive">
                <table class="table align-items-center table-flush">
                  <thead class="thead-light">
                    <tr>
                      <!-- <th scope="col">Client_Id</th> -->
                      <th scope="col">Client Name</th>
                      <th scope="col">Policy Type</th>
                      <th scope="col">Phone Number</th>
                      <th scope="col">Expire On</th>
                      <!-- <th scope="col">Policy_Number</th> -->
                      <!-- <th scope="col">Year_OF_Policy</th> -->
                      <!-- <th scope="col">Premium</th> -->
                      <!-- <th scope="col">Status</th> -->
                      <!-- <th scope="col">Actions</th> -->
                    </tr>
                  </thead>
                  <tbody>
                    {% for obj in towDaysDues %}
                    <tr>

                      <td>{{ obj.first_name }}</td>
                      <td>
                        {{ obj.get_policy_type_display }}
                      </td>
                      <td>
                        {{ obj.contact }}
                      </td>
                      <td>
                        <span class="badge badge-dot mr-4">
                          <i class="bg-warning"></i> {{ obj.renew_date }}
                        </span>
                      </td>

                    </tr>

                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>

            </div>
            <div class="col-md-6">
              <marquee behavior="scroll" direction="up" scrollamount="2"><h3 style="color: red" class="mb-0">Expire in 7 Days</h3></marquee>
              <br>
              <div class="table-responsive">
                <table class="table align-items-center table-flush">
                  <thead class="thead-light">
                    <tr>
                      <!-- <th scope="col">Client_Id</th> -->
                      <th scope="col">Client Name</th>
                      <th scope="col">Policy Type</th>
                      <th scope="col">Phone Number</th>
                      <th scope="col">Expire On</th>
                      <!-- <th scope="col">Policy_Number</th> -->
                      <!-- <th scope="col">Year_OF_Policy</th> -->
                      <!-- <th scope="col">Premium</th> -->
                      <!-- <th scope="col">Status</th> -->
                      <!-- <th scope="col">Actions</th> -->
                    </tr>
                  </thead>
                  <tbody>
                    {% for obj in weekDues %}
                    <tr>

                      <td>{{ obj.first_name }}</td>
                      <td>
                        {{ obj.get_policy_type_display }}
                      </td>
                      <td>
                        {{ obj.contact }}
                      </td>
                      <td>
                        <span class="badge badge-dot mr-4">
                          <i class="bg-warning"></i> {{ obj.renew_date }}
                        </span>
                      </td>

                    </tr>

                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% include "dashboard/footer.html" %}

</div> 

{% endblock content %}

dashboard/templates/dashboard/search_results.html
{% extends 'dashboard/base.html' %}


{% block content %}

<style type="text/css">
  .table .thead-light th {
    background-color: #f6f9fc;
    color: black;
  }  
</style>


<div class="container-fluid mt--7">

  <!-- Table -->
  <div class="row">
    <div class="col">
      <div class="card shadow">
        <div class="card-header border-0">
          <h3 class="mb-0">Show-Policy</h3>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <!-- <th scope="col">Client_Id</th> -->
                <th scope="col">Client_Name</th>
                <th scope="col">Policy_Type</th>
                <th scope="col">Policy_Number</th>
                <th scope="col">Year_OF_Policy</th>
                <th scope="col">Premium</th>
                <th scope="col">Status</th>
                <th scope="col">Actions</th>                
              </tr>
            </thead>
            <tbody>
              {% for lic in object_list %}  
              <tr>
                
                <td>{{ lic.first_name }}</td>
                <td>
                  {{ lic.get_policy_type_display }}
                </td>
                <td>
                  <span class="badge badge-dot mr-4">
                    <i class="bg-warning"></i> {{ lic.policy_number }}
                  </span>
                </td>
                <td>
                  <span class="badge badge-dot mr-4">
                    <i class="bg-warning"></i> {{ lic.year_of_policy }}
                  </span>
                </td> 
                
                <td>
                  <div class="d-flex align-items-center">
                    <span class="mr-2">{{ lic.premium }}</span>
                    
                  </div>
                </td>
                
                <td>
                  <div class="d-flex align-items-center">
                    <span class="mr-2">{{ lic.get_status_display }}</span>
                    
                  </div>
                </td>  
                <td>
                  <div class="d-flex align-items-center">
                    <a style="color:blue" href="/edit_policy/{{ lic.id }}"><span class="glyphicon glyphicon-pencil" >Edit--</span></a>  
                    <a style="color: red" href="/delete_policy/{{ lic.id }}">Delete</a>  

                  </div>
                </td> 
              </div>
            </td>
          </tr>

        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div> 
</div>
</div>
</div> 

{% include "dashboard/footer.html" %}

</div>

{% endblock content %}